export const metricMonths = [
  "JANEIRO",
  "FEVEREIRO",
  "MARÇO",
  "ABRIL",
  "MAIO",
  "JUNHO",
  "JULHO",
  "AGOSTO",
  "SETEMBRO",
  "OUTUBRO",
  "NOVEMBRO",
  "DEZEMBRO"
];

export const socialMetricMonthlyRows = [
  {
    "client": "A VIA DA CONSCIÊNCIA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 228,
    "newFollowers": 51,
    "losses": 125,
    "reach": 796,
    "views": 16,
    "engagement": 187,
    "visits": 33,
    "interactions": 30,
    "likes": 0,
    "comments": 0,
    "shares": 3,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "A VIA DA CONSCIÊNCIA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 234,
    "newFollowers": 11,
    "losses": 236,
    "reach": 675,
    "views": 31,
    "engagement": 77,
    "visits": 98,
    "interactions": 42,
    "likes": 27,
    "comments": 0,
    "shares": 29,
    "saves": 1,
    "linkTaps": null
  },
  {
    "client": "A VIA DA CONSCIÊNCIA",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 232,
    "newFollowers": 2,
    "losses": 3,
    "reach": 22,
    "views": 0,
    "engagement": 10,
    "visits": 0,
    "interactions": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "ADOLFO STURARO",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 2380,
    "newFollowers": 100,
    "losses": 28,
    "reach": 6084,
    "views": 28592,
    "engagement": 504,
    "visits": null,
    "interactions": 1086,
    "likes": 800,
    "comments": 38,
    "shares": 86,
    "saves": 17,
    "linkTaps": 1
  },
  {
    "client": "ADOLFO STURARO",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 2485,
    "newFollowers": 129,
    "losses": 24,
    "reach": 16757,
    "views": 66934,
    "engagement": 486,
    "visits": null,
    "interactions": 677,
    "likes": 490,
    "comments": 77,
    "shares": 35,
    "saves": 16,
    "linkTaps": 0
  },
  {
    "client": "ADOLFO STURARO",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 2572,
    "newFollowers": 111,
    "losses": 24,
    "reach": 15794,
    "views": 69537,
    "engagement": 513,
    "visits": null,
    "interactions": 1126,
    "likes": 976,
    "comments": 43,
    "shares": 37,
    "saves": 10,
    "linkTaps": 1
  },
  {
    "client": "ADOLFO STURARO",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 2660,
    "newFollowers": 109,
    "losses": 22,
    "reach": 13701,
    "views": 49753,
    "engagement": 377,
    "visits": null,
    "interactions": 719,
    "likes": 621,
    "comments": 41,
    "shares": 21,
    "saves": 6,
    "linkTaps": 4
  },
  {
    "client": "ADOLFO STURARO",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 2740,
    "newFollowers": 108,
    "losses": 29,
    "reach": 15211,
    "views": 42974,
    "engagement": 284,
    "visits": null,
    "interactions": 643,
    "likes": 527,
    "comments": 9,
    "shares": 39,
    "saves": 11,
    "linkTaps": 0
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 4392,
    "newFollowers": 27,
    "losses": 46,
    "reach": 3154,
    "views": 10883,
    "engagement": 73,
    "visits": null,
    "interactions": 136,
    "likes": 103,
    "comments": 4,
    "shares": 7,
    "saves": 2,
    "linkTaps": 1
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 4380,
    "newFollowers": 19,
    "losses": 32,
    "reach": 1967,
    "views": 6211,
    "engagement": 44,
    "visits": null,
    "interactions": 50,
    "likes": 41,
    "comments": 0,
    "shares": 1,
    "saves": 2,
    "linkTaps": 0
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 4381,
    "newFollowers": 37,
    "losses": 36,
    "reach": 2231,
    "views": 11598,
    "engagement": 81,
    "visits": null,
    "interactions": 173,
    "likes": 70,
    "comments": 3,
    "shares": 2,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 4386,
    "newFollowers": 42,
    "losses": 37,
    "reach": 2152,
    "views": 6971,
    "engagement": 69,
    "visits": null,
    "interactions": 124,
    "likes": 40,
    "comments": 3,
    "shares": 4,
    "saves": 3,
    "linkTaps": 0
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 4308,
    "newFollowers": 45,
    "losses": 123,
    "reach": 9849,
    "views": 25242,
    "engagement": 378,
    "visits": null,
    "interactions": 930,
    "likes": 729,
    "comments": 69,
    "shares": 32,
    "saves": 3,
    "linkTaps": 1
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 4307,
    "newFollowers": 35,
    "losses": 36,
    "reach": 3050,
    "views": 10862,
    "engagement": 120,
    "visits": null,
    "interactions": 441,
    "likes": 335,
    "comments": 21,
    "shares": 22,
    "saves": 2,
    "linkTaps": 0
  },
  {
    "client": "ADRIANA SANTOS",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 4305,
    "newFollowers": 28,
    "losses": 31,
    "reach": 1541,
    "views": 5803,
    "engagement": 62,
    "visits": null,
    "interactions": 309,
    "likes": 237,
    "comments": 2,
    "shares": 6,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "APTAMENTE",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 172,
    "newFollowers": 31,
    "losses": 6,
    "reach": 367,
    "views": 2811,
    "engagement": 57,
    "visits": 26,
    "interactions": 174,
    "likes": 128,
    "comments": 10,
    "shares": 2,
    "saves": 24,
    "linkTaps": 0
  },
  {
    "client": "APTAMENTE",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 218,
    "newFollowers": 53,
    "losses": 7,
    "reach": 1341,
    "views": 4350,
    "engagement": 44,
    "visits": 0,
    "interactions": 139,
    "likes": 113,
    "comments": 0,
    "shares": 3,
    "saves": 20,
    "linkTaps": 0
  },
  {
    "client": "APTAMENTE",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 251,
    "newFollowers": 44,
    "losses": 11,
    "reach": 936,
    "views": 5001,
    "engagement": 68,
    "visits": null,
    "interactions": 254,
    "likes": 207,
    "comments": 13,
    "shares": 1,
    "saves": 27,
    "linkTaps": 0
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 1773,
    "newFollowers": 100,
    "losses": 20,
    "reach": 156075,
    "views": 309369,
    "engagement": 180,
    "visits": 73,
    "interactions": 233,
    "likes": 198,
    "comments": 1,
    "shares": 14,
    "saves": 17,
    "linkTaps": 13
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 1844,
    "newFollowers": 93,
    "losses": 18,
    "reach": 100112,
    "views": 185992,
    "engagement": 551,
    "visits": 0,
    "interactions": 824,
    "likes": 696,
    "comments": 45,
    "shares": 22,
    "saves": 57,
    "linkTaps": 0
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 1932,
    "newFollowers": 102,
    "losses": 18,
    "reach": 74817,
    "views": 134707,
    "engagement": 353,
    "visits": null,
    "interactions": 464,
    "likes": 405,
    "comments": 21,
    "shares": 14,
    "saves": 23,
    "linkTaps": 3
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 2317,
    "newFollowers": 412,
    "losses": 25,
    "reach": 143129,
    "views": 133160,
    "engagement": 788,
    "visits": null,
    "interactions": 1023,
    "likes": 890,
    "comments": 34,
    "shares": 49,
    "saves": 45,
    "linkTaps": 5
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 2788,
    "newFollowers": 499,
    "losses": 29,
    "reach": 217561,
    "views": 762122,
    "engagement": 1088,
    "visits": null,
    "interactions": 1542,
    "likes": 1334,
    "comments": 54,
    "shares": 46,
    "saves": 98,
    "linkTaps": 7
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 2971,
    "newFollowers": 213,
    "losses": 37,
    "reach": 196552,
    "views": 768349,
    "engagement": 378,
    "visits": null,
    "interactions": 549,
    "likes": 406,
    "comments": 13,
    "shares": 23,
    "saves": 48,
    "linkTaps": 10
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 3209,
    "newFollowers": 270,
    "losses": 29,
    "reach": 182574,
    "views": 654388,
    "engagement": 801,
    "visits": null,
    "interactions": 1015,
    "likes": 860,
    "comments": 35,
    "shares": 21,
    "saves": 45,
    "linkTaps": 9
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 3316,
    "newFollowers": 146,
    "losses": 36,
    "reach": 106038,
    "views": 331890,
    "engagement": 409,
    "visits": null,
    "interactions": 515,
    "likes": 396,
    "comments": 8,
    "shares": 16,
    "saves": 50,
    "linkTaps": 10
  },
  {
    "client": "ARTRUS",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 3498,
    "newFollowers": 210,
    "losses": 28,
    "reach": 170015,
    "views": 652338,
    "engagement": 766,
    "visits": null,
    "interactions": 1098,
    "likes": 921,
    "comments": 52,
    "shares": 26,
    "saves": 41,
    "linkTaps": 4
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 3269,
    "newFollowers": 92,
    "losses": 36,
    "reach": 90057,
    "views": 153117,
    "engagement": 214,
    "visits": null,
    "interactions": 322,
    "likes": 263,
    "comments": 12,
    "shares": 15,
    "saves": 9,
    "linkTaps": 35
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 3310,
    "newFollowers": 76,
    "losses": 34,
    "reach": 80071,
    "views": 140680,
    "engagement": 302,
    "visits": null,
    "interactions": 477,
    "likes": 333,
    "comments": 58,
    "shares": 36,
    "saves": 1,
    "linkTaps": 22
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 3350,
    "newFollowers": 84,
    "losses": 43,
    "reach": 3145,
    "views": 10552,
    "engagement": 104,
    "visits": null,
    "interactions": 178,
    "likes": 110,
    "comments": 4,
    "shares": 25,
    "saves": 9,
    "linkTaps": 28
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 3403,
    "newFollowers": 95,
    "losses": 43,
    "reach": 3094,
    "views": 18633,
    "engagement": 139,
    "visits": null,
    "interactions": 257,
    "likes": 228,
    "comments": 25,
    "shares": 38,
    "saves": 5,
    "linkTaps": 18
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 3434,
    "newFollowers": 91,
    "losses": 59,
    "reach": 5340,
    "views": 19018,
    "engagement": 179,
    "visits": null,
    "interactions": 326,
    "likes": 252,
    "comments": 20,
    "shares": 21,
    "saves": 6,
    "linkTaps": 20
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 3466,
    "newFollowers": 69,
    "losses": 38,
    "reach": 2325,
    "views": 9621,
    "engagement": 39,
    "visits": null,
    "interactions": 71,
    "likes": 58,
    "comments": 2,
    "shares": 4,
    "saves": 3,
    "linkTaps": 18
  },
  {
    "client": "CARDIOCENTER",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 3561,
    "newFollowers": 132,
    "losses": 37,
    "reach": 9335,
    "views": 78040,
    "engagement": 74,
    "visits": null,
    "interactions": 103,
    "likes": 67,
    "comments": 4,
    "shares": 13,
    "saves": 5,
    "linkTaps": 32
  },
  {
    "client": "DAIANE SOUZA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 5274,
    "newFollowers": 101,
    "losses": 56,
    "reach": 24368,
    "views": 70089,
    "engagement": 198,
    "visits": null,
    "interactions": 394,
    "likes": 309,
    "comments": 21,
    "shares": 7,
    "saves": 2,
    "linkTaps": 0
  },
  {
    "client": "DAIANE SOUZA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 5328,
    "newFollowers": 111,
    "losses": 57,
    "reach": 10002,
    "views": 65706,
    "engagement": 208,
    "visits": null,
    "interactions": 285,
    "likes": 209,
    "comments": 3,
    "shares": 8,
    "saves": 6,
    "linkTaps": 0
  },
  {
    "client": "CHAVES E MATOS ADV",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 371,
    "newFollowers": 18,
    "losses": 1014,
    "reach": 3355,
    "views": 70,
    "engagement": 99,
    "visits": 142,
    "interactions": 124,
    "likes": 1,
    "comments": 5,
    "shares": 11,
    "saves": 1,
    "linkTaps": null
  },
  {
    "client": "CHAVES E MATOS ADV",
    "access": "Ativo",
    "month": "OUTUBRO",
    "followers": 380,
    "newFollowers": 14,
    "losses": 667,
    "reach": 3203,
    "views": 90,
    "engagement": 134,
    "visits": 227,
    "interactions": 204,
    "likes": 3,
    "comments": 9,
    "shares": 6,
    "saves": 8,
    "linkTaps": null
  },
  {
    "client": "CHAVES E MATOS ADV",
    "access": "Ativo",
    "month": "NOVEMBRO",
    "followers": 388,
    "newFollowers": 13,
    "losses": 497,
    "reach": 3229,
    "views": 59,
    "engagement": 90,
    "visits": 177,
    "interactions": 158,
    "likes": 0,
    "comments": 13,
    "shares": 5,
    "saves": 5,
    "linkTaps": null
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 2052,
    "newFollowers": 81,
    "losses": 25,
    "reach": 2815,
    "views": 11109,
    "engagement": 42,
    "visits": 83,
    "interactions": 72,
    "likes": 64,
    "comments": 0,
    "shares": 4,
    "saves": 3,
    "linkTaps": 35
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": null,
    "newFollowers": 77,
    "losses": 10,
    "reach": 2942,
    "views": 8103,
    "engagement": 316,
    "visits": 0,
    "interactions": 246,
    "likes": 215,
    "comments": 17,
    "shares": 1,
    "saves": 11,
    "linkTaps": 18
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 2233,
    "newFollowers": 95,
    "losses": 20,
    "reach": 3834,
    "views": 15446,
    "engagement": 310,
    "visits": null,
    "interactions": 439,
    "likes": 369,
    "comments": 17,
    "shares": 6,
    "saves": 32,
    "linkTaps": 12
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 2318,
    "newFollowers": 112,
    "losses": 25,
    "reach": 2584,
    "views": 5114,
    "engagement": 257,
    "visits": null,
    "interactions": 349,
    "likes": 302,
    "comments": 20,
    "shares": 5,
    "saves": 14,
    "linkTaps": 23
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 2386,
    "newFollowers": 93,
    "losses": 26,
    "reach": 1290,
    "views": 8003,
    "engagement": 55,
    "visits": null,
    "interactions": 87,
    "likes": 65,
    "comments": 5,
    "shares": 4,
    "saves": 13,
    "linkTaps": 12
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 2468,
    "newFollowers": 105,
    "losses": 25,
    "reach": 2494,
    "views": 9188,
    "engagement": 208,
    "visits": null,
    "interactions": 312,
    "likes": 216,
    "comments": 19,
    "shares": 6,
    "saves": 35,
    "linkTaps": 20
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 2542,
    "newFollowers": 93,
    "losses": 21,
    "reach": 2437,
    "views": 21789,
    "engagement": 224,
    "visits": null,
    "interactions": 336,
    "likes": 274,
    "comments": 7,
    "shares": 7,
    "saves": 22,
    "linkTaps": 15
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 2766,
    "newFollowers": 253,
    "losses": 26,
    "reach": 55477,
    "views": 285336,
    "engagement": 307,
    "visits": null,
    "interactions": 416,
    "likes": 315,
    "comments": 21,
    "shares": 13,
    "saves": 24,
    "linkTaps": 44
  },
  {
    "client": "CLIORT",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 2916,
    "newFollowers": 178,
    "losses": 28,
    "reach": 46481,
    "views": 86780,
    "engagement": 239,
    "visits": null,
    "interactions": 278,
    "likes": 249,
    "comments": 3,
    "shares": 5,
    "saves": 7,
    "linkTaps": 27
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 14994,
    "newFollowers": 426,
    "losses": 167,
    "reach": 22895,
    "views": 181328,
    "engagement": 1145,
    "visits": null,
    "interactions": 2066,
    "likes": 1371,
    "comments": 50,
    "shares": 94,
    "saves": 65,
    "linkTaps": 10
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 15395,
    "newFollowers": 547,
    "losses": 143,
    "reach": 146886,
    "views": 386105,
    "engagement": 7292,
    "visits": null,
    "interactions": 12657,
    "likes": 7378,
    "comments": 224,
    "shares": 2052,
    "saves": 389,
    "linkTaps": 22
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 15904,
    "newFollowers": 666,
    "losses": 160,
    "reach": 79245,
    "views": 373509,
    "engagement": 3428,
    "visits": null,
    "interactions": 7350,
    "likes": 4614,
    "comments": 143,
    "shares": 819,
    "saves": 254,
    "linkTaps": 25
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 16109,
    "newFollowers": 368,
    "losses": 160,
    "reach": 36350,
    "views": 217632,
    "engagement": 2457,
    "visits": null,
    "interactions": 4496,
    "likes": 3228,
    "comments": 159,
    "shares": 297,
    "saves": 93,
    "linkTaps": 22
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 16328,
    "newFollowers": 427,
    "losses": 207,
    "reach": 39355,
    "views": 195698,
    "engagement": 1707,
    "visits": null,
    "interactions": 4651,
    "likes": 3528,
    "comments": 95,
    "shares": 287,
    "saves": 125,
    "linkTaps": 18
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 16687,
    "newFollowers": 546,
    "losses": 192,
    "reach": 40896,
    "views": 164848,
    "engagement": 1820,
    "visits": null,
    "interactions": 3988,
    "likes": 3161,
    "comments": 56,
    "shares": 133,
    "saves": 124,
    "linkTaps": 12
  },
  {
    "client": "DANIELA MOURA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 17120,
    "newFollowers": 671,
    "losses": 236,
    "reach": 54185,
    "views": 244892,
    "engagement": 1632,
    "visits": null,
    "interactions": 4970,
    "likes": 3690,
    "comments": 75,
    "shares": 253,
    "saves": 229,
    "linkTaps": 11
  },
  {
    "client": "ESPAÇO FAZER MAIS",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 950,
    "newFollowers": 16,
    "losses": 6,
    "reach": 1507,
    "views": 5044,
    "engagement": 30,
    "visits": null,
    "interactions": 59,
    "likes": 56,
    "comments": 0,
    "shares": 1,
    "saves": 1,
    "linkTaps": 4
  },
  {
    "client": "ESPAÇO FAZER MAIS",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 964,
    "newFollowers": 22,
    "losses": 7,
    "reach": 12803,
    "views": 25407,
    "engagement": 138,
    "visits": null,
    "interactions": 217,
    "likes": 176,
    "comments": 17,
    "shares": 5,
    "saves": 7,
    "linkTaps": 7
  },
  {
    "client": "ESPAÇO FAZER MAIS",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 1009,
    "newFollowers": 44,
    "losses": 3,
    "reach": 4251,
    "views": 14257,
    "engagement": 39,
    "visits": null,
    "interactions": 74,
    "likes": 45,
    "comments": 0,
    "shares": 27,
    "saves": 1,
    "linkTaps": 28
  },
  {
    "client": "ESPAÇO FAZER MAIS",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 1026,
    "newFollowers": 32,
    "losses": 11,
    "reach": 3961,
    "views": 14211,
    "engagement": 88,
    "visits": null,
    "interactions": 109,
    "likes": 76,
    "comments": 9,
    "shares": 13,
    "saves": 2,
    "linkTaps": 13
  },
  {
    "client": "ESPAÇO FAZER MAIS",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 1043,
    "newFollowers": 23,
    "losses": 6,
    "reach": 6934,
    "views": 28803,
    "engagement": 29,
    "visits": null,
    "interactions": 36,
    "likes": 30,
    "comments": 0,
    "shares": 0,
    "saves": 3,
    "linkTaps": 6
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 319,
    "newFollowers": 5,
    "losses": 1,
    "reach": 649,
    "views": 5616,
    "engagement": 56,
    "visits": null,
    "interactions": 166,
    "likes": 106,
    "comments": 16,
    "shares": 15,
    "saves": 10,
    "linkTaps": 0
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 324,
    "newFollowers": 6,
    "losses": 1,
    "reach": 408,
    "views": 2392,
    "engagement": 36,
    "visits": null,
    "interactions": 109,
    "likes": 85,
    "comments": 11,
    "shares": 5,
    "saves": 2,
    "linkTaps": 0
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 325,
    "newFollowers": 3,
    "losses": 2,
    "reach": 456,
    "views": 1144,
    "engagement": 28,
    "visits": null,
    "interactions": 88,
    "likes": 54,
    "comments": 13,
    "shares": 9,
    "saves": 3,
    "linkTaps": 1
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 333,
    "newFollowers": 8,
    "losses": 0,
    "reach": 283,
    "views": 1562,
    "engagement": 16,
    "visits": null,
    "interactions": 63,
    "likes": 44,
    "comments": 3,
    "shares": 7,
    "saves": 0,
    "linkTaps": 0
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 372,
    "newFollowers": 45,
    "losses": 6,
    "reach": 1140,
    "views": 4422,
    "engagement": 94,
    "visits": null,
    "interactions": 286,
    "likes": 208,
    "comments": 28,
    "shares": 20,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 373,
    "newFollowers": 2,
    "losses": 1,
    "reach": 277,
    "views": 852,
    "engagement": 19,
    "visits": null,
    "interactions": 68,
    "likes": 51,
    "comments": 10,
    "shares": 3,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "FATURE MAIS",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 367,
    "newFollowers": 2,
    "losses": 8,
    "reach": 168,
    "views": 1027,
    "engagement": 21,
    "visits": null,
    "interactions": 72,
    "likes": 51,
    "comments": 5,
    "shares": 8,
    "saves": 0,
    "linkTaps": 0
  },
  {
    "client": "GEEMED",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 601,
    "newFollowers": 7,
    "losses": 6,
    "reach": 239,
    "views": 1540,
    "engagement": 14,
    "visits": 89,
    "interactions": 87,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "GEEMED",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 599,
    "newFollowers": 5,
    "losses": 8,
    "reach": 237,
    "views": 1822,
    "engagement": 20,
    "visits": 75,
    "interactions": 74,
    "likes": 1,
    "comments": 0,
    "shares": 0,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "GEEMED",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 597,
    "newFollowers": 9,
    "losses": 11,
    "reach": 181,
    "views": 1054,
    "engagement": 21,
    "visits": 69,
    "interactions": 65,
    "likes": 2,
    "comments": 0,
    "shares": 1,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 14572,
    "newFollowers": 294,
    "losses": 116,
    "reach": 28467,
    "views": 161686,
    "engagement": 2484,
    "visits": null,
    "interactions": 3866,
    "likes": 3088,
    "comments": 167,
    "shares": 113,
    "saves": 36,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 15627,
    "newFollowers": 1197,
    "losses": 143,
    "reach": 77059,
    "views": 306199,
    "engagement": 4616,
    "visits": null,
    "interactions": 8133,
    "likes": 6503,
    "comments": 482,
    "shares": 139,
    "saves": 155,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 16487,
    "newFollowers": 1007,
    "losses": 147,
    "reach": 91770,
    "views": 380264,
    "engagement": 4046,
    "visits": null,
    "interactions": 8711,
    "likes": 6592,
    "comments": 279,
    "shares": 486,
    "saves": 171,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 17304,
    "newFollowers": 988,
    "losses": 170,
    "reach": 84736,
    "views": 376524,
    "engagement": 5982,
    "visits": null,
    "interactions": 12065,
    "likes": 8994,
    "comments": 640,
    "shares": 670,
    "saves": 116,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 17537,
    "newFollowers": 440,
    "losses": 210,
    "reach": 34464,
    "views": 302850,
    "engagement": 4588,
    "visits": null,
    "interactions": 11446,
    "likes": 9082,
    "comments": 325,
    "shares": 688,
    "saves": 84,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 17877,
    "newFollowers": 503,
    "losses": 158,
    "reach": 59455,
    "views": 255213,
    "engagement": 2741,
    "visits": null,
    "interactions": 6457,
    "likes": 5344,
    "comments": 137,
    "shares": 271,
    "saves": 60,
    "linkTaps": 0
  },
  {
    "client": "GILVAN LANDIM",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 18102,
    "newFollowers": 100,
    "losses": 178,
    "reach": 22983,
    "views": 216811,
    "engagement": 2389,
    "visits": null,
    "interactions": 7854,
    "likes": 5753,
    "comments": 233,
    "shares": 561,
    "saves": 73,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 3440,
    "newFollowers": 371,
    "losses": 65,
    "reach": 164378,
    "views": 470220,
    "engagement": 438,
    "visits": null,
    "interactions": 812,
    "likes": 447,
    "comments": 26,
    "shares": 97,
    "saves": 85,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 3644,
    "newFollowers": 258,
    "losses": 50,
    "reach": 85124,
    "views": 270569,
    "engagement": 390,
    "visits": null,
    "interactions": 726,
    "likes": 366,
    "comments": 32,
    "shares": 104,
    "saves": 37,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 4307,
    "newFollowers": 723,
    "losses": 67,
    "reach": 109494,
    "views": 410749,
    "engagement": 1056,
    "visits": null,
    "interactions": 2768,
    "likes": 1503,
    "comments": 173,
    "shares": 377,
    "saves": 98,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 4756,
    "newFollowers": 530,
    "losses": 74,
    "reach": 23696,
    "views": 161382,
    "engagement": 875,
    "visits": null,
    "interactions": 1656,
    "likes": 1019,
    "comments": 69,
    "shares": 184,
    "saves": 73,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 5167,
    "newFollowers": 503,
    "losses": 101,
    "reach": 19926,
    "views": 153305,
    "engagement": 723,
    "visits": null,
    "interactions": 2258,
    "likes": 1508,
    "comments": 87,
    "shares": 272,
    "saves": 49,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 5645,
    "newFollowers": 595,
    "losses": 120,
    "reach": 26238,
    "views": 187450,
    "engagement": 977,
    "visits": null,
    "interactions": 2655,
    "likes": 1861,
    "comments": 94,
    "shares": 260,
    "saves": 65,
    "linkTaps": 0
  },
  {
    "client": "IL DISTRIBUIDORA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 6248,
    "newFollowers": 723,
    "losses": 115,
    "reach": 26616,
    "views": 234540,
    "engagement": 714,
    "visits": null,
    "interactions": 2263,
    "likes": 1548,
    "comments": 46,
    "shares": 250,
    "saves": 76,
    "linkTaps": 0
  },
  {
    "client": "IANN",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 84,
    "newFollowers": 12,
    "losses": 0,
    "reach": 2234,
    "views": 6614,
    "engagement": 278,
    "visits": 12,
    "interactions": 753,
    "likes": 542,
    "comments": 34,
    "shares": 11,
    "saves": 162,
    "linkTaps": 2
  },
  {
    "client": "IANN",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 154,
    "newFollowers": 72,
    "losses": 1,
    "reach": 1314,
    "views": 8460,
    "engagement": 264,
    "visits": null,
    "interactions": 726,
    "likes": 589,
    "comments": 32,
    "shares": 17,
    "saves": 79,
    "linkTaps": 0
  },
  {
    "client": "IANN",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 176,
    "newFollowers": 26,
    "losses": 4,
    "reach": 2723,
    "views": 9474,
    "engagement": 205,
    "visits": null,
    "interactions": 577,
    "likes": 460,
    "comments": 37,
    "shares": 9,
    "saves": 59,
    "linkTaps": 0
  },
  {
    "client": "IANN",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 179,
    "newFollowers": 4,
    "losses": 2,
    "reach": 801,
    "views": 2006,
    "engagement": 128,
    "visits": null,
    "interactions": 392,
    "likes": 324,
    "comments": 24,
    "shares": 5,
    "saves": 33,
    "linkTaps": 0
  },
  {
    "client": "IANN",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 188,
    "newFollowers": 12,
    "losses": 2,
    "reach": 404,
    "views": 1249,
    "engagement": 57,
    "visits": null,
    "interactions": 68,
    "likes": 58,
    "comments": 5,
    "shares": 1,
    "saves": 4,
    "linkTaps": 0
  },
  {
    "client": "HENRIQUE CHAVES",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 2289,
    "newFollowers": 54,
    "losses": 28651,
    "reach": 42852,
    "views": 150,
    "engagement": 871,
    "visits": 454,
    "interactions": 289,
    "likes": 36,
    "comments": 18,
    "shares": 32,
    "saves": 31,
    "linkTaps": null
  },
  {
    "client": "HENRIQUE CHAVES",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 2333,
    "newFollowers": 78,
    "losses": 15900,
    "reach": 32164,
    "views": 181,
    "engagement": 928,
    "visits": 340,
    "interactions": 231,
    "likes": 4,
    "comments": 11,
    "shares": 8,
    "saves": 14,
    "linkTaps": null
  },
  {
    "client": "HENRIQUE CHAVES",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 2342,
    "newFollowers": 28,
    "losses": 4227,
    "reach": 9624,
    "views": 118,
    "engagement": 280,
    "visits": 301,
    "interactions": 222,
    "likes": 15,
    "comments": 17,
    "shares": 2,
    "saves": 4,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 10283,
    "newFollowers": 214,
    "losses": 7583,
    "reach": 27091,
    "views": 469,
    "engagement": 1144,
    "visits": 850,
    "interactions": 762,
    "likes": 25,
    "comments": 22,
    "shares": 34,
    "saves": 121,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 10397,
    "newFollowers": 236,
    "losses": 13460,
    "reach": 25742,
    "views": 1129,
    "engagement": 1053,
    "visits": 1720,
    "interactions": 1573,
    "likes": 52,
    "comments": 40,
    "shares": 49,
    "saves": 82,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 10530,
    "newFollowers": 221,
    "losses": 7690,
    "reach": 18529,
    "views": 272,
    "engagement": 913,
    "visits": 498,
    "interactions": 419,
    "likes": 3,
    "comments": 27,
    "shares": 48,
    "saves": 61,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 10648,
    "newFollowers": 220,
    "losses": 5501,
    "reach": 14128,
    "views": 166,
    "engagement": 885,
    "visits": 375,
    "interactions": 338,
    "likes": 5,
    "comments": 9,
    "shares": 20,
    "saves": 85,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 10735,
    "newFollowers": 205,
    "losses": 4869,
    "reach": 14045,
    "views": 218,
    "engagement": 888,
    "visits": 317,
    "interactions": 254,
    "likes": 24,
    "comments": 18,
    "shares": 18,
    "saves": 71,
    "linkTaps": null
  },
  {
    "client": "HOSPITAL DA PLÁSTICA DA BAHIA",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 10868,
    "newFollowers": 233,
    "losses": 4120,
    "reach": 15586,
    "views": 198,
    "engagement": 967,
    "visits": 389,
    "interactions": 316,
    "likes": 20,
    "comments": 5,
    "shares": 44,
    "saves": 98,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 868,
    "newFollowers": 36,
    "losses": 635,
    "reach": 2680,
    "views": 64,
    "engagement": 214,
    "visits": 109,
    "interactions": 96,
    "likes": 2,
    "comments": 3,
    "shares": 6,
    "saves": 19,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 869,
    "newFollowers": 12,
    "losses": 488,
    "reach": 1630,
    "views": 48,
    "engagement": 106,
    "visits": 85,
    "interactions": 80,
    "likes": 1,
    "comments": 1,
    "shares": 3,
    "saves": 6,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 896,
    "newFollowers": 32,
    "losses": 2252,
    "reach": 6348,
    "views": 223,
    "engagement": 215,
    "visits": 414,
    "interactions": 330,
    "likes": 9,
    "comments": 3,
    "shares": 71,
    "saves": 17,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 910,
    "newFollowers": 25,
    "losses": 530,
    "reach": 2158,
    "views": 65,
    "engagement": 182,
    "visits": 132,
    "interactions": 109,
    "likes": 6,
    "comments": 5,
    "shares": 12,
    "saves": 14,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 927,
    "newFollowers": 26,
    "losses": 1059,
    "reach": 3330,
    "views": 85,
    "engagement": 207,
    "visits": 232,
    "interactions": 185,
    "likes": 5,
    "comments": 9,
    "shares": 33,
    "saves": 14,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 943,
    "newFollowers": 25,
    "losses": 967,
    "reach": 3626,
    "views": 63,
    "engagement": 145,
    "visits": 181,
    "interactions": 167,
    "likes": 5,
    "comments": 5,
    "shares": 4,
    "saves": 5,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 956,
    "newFollowers": 25,
    "losses": 424,
    "reach": 1727,
    "views": 40,
    "engagement": 169,
    "visits": 128,
    "interactions": 113,
    "likes": 6,
    "comments": 4,
    "shares": 5,
    "saves": 16,
    "linkTaps": null
  },
  {
    "client": "INH",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 967,
    "newFollowers": 14,
    "losses": 1098,
    "reach": 2893,
    "views": 75,
    "engagement": 134,
    "visits": 176,
    "interactions": 151,
    "likes": 13,
    "comments": 6,
    "shares": 6,
    "saves": 4,
    "linkTaps": null
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 3320,
    "newFollowers": 95,
    "losses": 23,
    "reach": 11494,
    "views": 24190,
    "engagement": 157,
    "visits": null,
    "interactions": 241,
    "likes": 185,
    "comments": 2,
    "shares": 16,
    "saves": 10,
    "linkTaps": 4
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 3397,
    "newFollowers": 98,
    "losses": 21,
    "reach": 13573,
    "views": 29990,
    "engagement": 278,
    "visits": null,
    "interactions": 385,
    "likes": 312,
    "comments": 15,
    "shares": 18,
    "saves": 16,
    "linkTaps": 4
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 3558,
    "newFollowers": 183,
    "losses": 22,
    "reach": 21977,
    "views": 61608,
    "engagement": 678,
    "visits": null,
    "interactions": 1411,
    "likes": 820,
    "comments": 32,
    "shares": 246,
    "saves": 44,
    "linkTaps": 9
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 3645,
    "newFollowers": 109,
    "losses": 23,
    "reach": 18636,
    "views": 49509,
    "engagement": 781,
    "visits": null,
    "interactions": 1326,
    "likes": 1097,
    "comments": 73,
    "shares": 50,
    "saves": 28,
    "linkTaps": 3
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 3749,
    "newFollowers": 137,
    "losses": 32,
    "reach": 37287,
    "views": 90780,
    "engagement": 879,
    "visits": null,
    "interactions": 1971,
    "likes": 1372,
    "comments": 78,
    "shares": 241,
    "saves": 33,
    "linkTaps": 4
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 3952,
    "newFollowers": 236,
    "losses": 33,
    "reach": 28988,
    "views": 55786,
    "engagement": 221,
    "visits": null,
    "interactions": 401,
    "likes": 247,
    "comments": 11,
    "shares": 49,
    "saves": 34,
    "linkTaps": 9
  },
  {
    "client": "INSTITUTO LANDIM",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 4014,
    "newFollowers": 94,
    "losses": 33,
    "reach": 25002,
    "views": 51338,
    "engagement": 201,
    "visits": null,
    "interactions": 313,
    "likes": 244,
    "comments": 6,
    "shares": 19,
    "saves": 21,
    "linkTaps": 3
  },
  {
    "client": "ISABOR SANTANNA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 1146,
    "newFollowers": 26,
    "losses": 15,
    "reach": 1967,
    "views": 5052,
    "engagement": 51,
    "visits": null,
    "interactions": 99,
    "likes": 82,
    "comments": 2,
    "shares": 6,
    "saves": 3,
    "linkTaps": 0
  },
  {
    "client": "ISABOR SANTANNA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 1167,
    "newFollowers": 30,
    "losses": 9,
    "reach": 4655,
    "views": 10872,
    "engagement": 62,
    "visits": null,
    "interactions": 87,
    "likes": 76,
    "comments": 2,
    "shares": 1,
    "saves": 7,
    "linkTaps": 5
  },
  {
    "client": "ISABOR SANTANNA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 1231,
    "newFollowers": 76,
    "losses": 12,
    "reach": 9711,
    "views": 30291,
    "engagement": 173,
    "visits": null,
    "interactions": 264,
    "likes": 207,
    "comments": 6,
    "shares": 11,
    "saves": 27,
    "linkTaps": 4
  },
  {
    "client": "LAZZO MATUMBI",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 187257,
    "newFollowers": 25115,
    "losses": 2088,
    "reach": 439212,
    "views": 8353291,
    "engagement": 460332,
    "visits": null,
    "interactions": 695550,
    "likes": 623864,
    "comments": 12259,
    "shares": 23255,
    "saves": 10257,
    "linkTaps": 0
  },
  {
    "client": "LAZZO MATUMBI",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 202863,
    "newFollowers": 18799,
    "losses": 3151,
    "reach": 555055,
    "views": 1945230,
    "engagement": 102642,
    "visits": null,
    "interactions": 205087,
    "likes": 144899,
    "comments": 4340,
    "shares": 21947,
    "saves": 5907,
    "linkTaps": 0
  },
  {
    "client": "LAZZO MATUMBI",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 206164,
    "newFollowers": 5921,
    "losses": 2649,
    "reach": 480512,
    "views": 1415211,
    "engagement": 62280,
    "visits": null,
    "interactions": 115052,
    "likes": 87954,
    "comments": 3073,
    "shares": 9222,
    "saves": 3604,
    "linkTaps": 0
  },
  {
    "client": "LAZZO MATUMBI",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 207612,
    "newFollowers": 3785,
    "losses": 2326,
    "reach": 413103,
    "views": 1338789,
    "engagement": 33210,
    "visits": null,
    "interactions": 67437,
    "likes": 46926,
    "comments": 1499,
    "shares": 8213,
    "saves": 1653,
    "linkTaps": 0
  },
  {
    "client": "LAZZO MATUMBI",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 208559,
    "newFollowers": 2504,
    "losses": 1460,
    "reach": null,
    "views": 173425,
    "engagement": null,
    "visits": null,
    "interactions": 20685,
    "likes": 16196,
    "comments": 477,
    "shares": 1551,
    "saves": 770,
    "linkTaps": 0
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 947,
    "newFollowers": 51,
    "losses": 15,
    "reach": 5163,
    "views": 13597,
    "engagement": 105,
    "visits": null,
    "interactions": 276,
    "likes": 183,
    "comments": 6,
    "shares": 32,
    "saves": 5,
    "linkTaps": 0
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 971,
    "newFollowers": 39,
    "losses": 14,
    "reach": 8887,
    "views": 14761,
    "engagement": 117,
    "visits": null,
    "interactions": 329,
    "likes": 280,
    "comments": 6,
    "shares": 14,
    "saves": 0,
    "linkTaps": 0
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 1123,
    "newFollowers": 165,
    "losses": 15,
    "reach": 31242,
    "views": 53195,
    "engagement": 378,
    "visits": null,
    "interactions": 940,
    "likes": 576,
    "comments": 139,
    "shares": 43,
    "saves": 76,
    "linkTaps": 1
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 1153,
    "newFollowers": 60,
    "losses": 28,
    "reach": 12449,
    "views": 27491,
    "engagement": 389,
    "visits": null,
    "interactions": 916,
    "likes": 529,
    "comments": 194,
    "shares": 67,
    "saves": 30,
    "linkTaps": 2
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 1318,
    "newFollowers": 186,
    "losses": 20,
    "reach": 5951,
    "views": 21669,
    "engagement": 675,
    "visits": null,
    "interactions": 1541,
    "likes": 1220,
    "comments": 102,
    "shares": 56,
    "saves": 73,
    "linkTaps": 1
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 1558,
    "newFollowers": 262,
    "losses": 23,
    "reach": 22257,
    "views": 36528,
    "engagement": 702,
    "visits": null,
    "interactions": 1233,
    "likes": 947,
    "comments": 41,
    "shares": 32,
    "saves": 153,
    "linkTaps": 1
  },
  {
    "client": "LUANDA RODRIGUES",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 1550,
    "newFollowers": 27,
    "losses": 35,
    "reach": 561,
    "views": 2918,
    "engagement": 44,
    "visits": null,
    "interactions": 100,
    "likes": 87,
    "comments": 2,
    "shares": 4,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "LUANE MATOS",
    "access": "Ativo",
    "month": "AGOSTO",
    "followers": 909,
    "newFollowers": 32,
    "losses": 4434,
    "reach": 31945,
    "views": 278,
    "engagement": 450,
    "visits": 912,
    "interactions": 588,
    "likes": 53,
    "comments": 4,
    "shares": 11,
    "saves": 4,
    "linkTaps": null
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 7114,
    "newFollowers": 194,
    "losses": 67,
    "reach": 42530,
    "views": 96409,
    "engagement": 453,
    "visits": null,
    "interactions": 598,
    "likes": 397,
    "comments": 19,
    "shares": 61,
    "saves": 21,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 7186,
    "newFollowers": 161,
    "losses": 92,
    "reach": 44508,
    "views": 112220,
    "engagement": 699,
    "visits": null,
    "interactions": 856,
    "likes": 691,
    "comments": 33,
    "shares": 41,
    "saves": 12,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 7309,
    "newFollowers": 209,
    "losses": 83,
    "reach": 36936,
    "views": 112868,
    "engagement": 600,
    "visits": null,
    "interactions": 996,
    "likes": 709,
    "comments": 54,
    "shares": 50,
    "saves": 25,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 7542,
    "newFollowers": 297,
    "losses": 63,
    "reach": 38823,
    "views": 107222,
    "engagement": 810,
    "visits": null,
    "interactions": 1089,
    "likes": 878,
    "comments": 46,
    "shares": 41,
    "saves": 21,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 7618,
    "newFollowers": 219,
    "losses": 144,
    "reach": 30524,
    "views": 81516,
    "engagement": 499,
    "visits": null,
    "interactions": 893,
    "likes": 711,
    "comments": 31,
    "shares": 50,
    "saves": 19,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 7613,
    "newFollowers": 89,
    "losses": 94,
    "reach": 4075,
    "views": 28051,
    "engagement": 1518,
    "visits": null,
    "interactions": 2070,
    "likes": 1920,
    "comments": 49,
    "shares": 27,
    "saves": 8,
    "linkTaps": 0
  },
  {
    "client": "LUCAS FRAGA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 7785,
    "newFollowers": 241,
    "losses": 68,
    "reach": 37381,
    "views": 90812,
    "engagement": 596,
    "visits": null,
    "interactions": 1252,
    "likes": 968,
    "comments": 53,
    "shares": 83,
    "saves": 25,
    "linkTaps": 0
  },
  {
    "client": "MAISA PAMPONET",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 11464,
    "newFollowers": 145,
    "losses": 102,
    "reach": 26208,
    "views": 70890,
    "engagement": 495,
    "visits": null,
    "interactions": 910,
    "likes": 695,
    "comments": 89,
    "shares": 37,
    "saves": 77,
    "linkTaps": 15
  },
  {
    "client": "MAISA PAMPONET",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 11552,
    "newFollowers": 201,
    "losses": 117,
    "reach": null,
    "views": 91368,
    "engagement": null,
    "visits": null,
    "interactions": 941,
    "likes": 642,
    "comments": 93,
    "shares": 68,
    "saves": 113,
    "linkTaps": 12
  },
  {
    "client": "LUDMILA MENDES",
    "access": "Ativo",
    "month": "SETEMBRO",
    "followers": 3489,
    "newFollowers": 861,
    "losses": 2058,
    "reach": 36487,
    "views": 86494,
    "engagement": 271,
    "visits": null,
    "interactions": 544,
    "likes": 295,
    "comments": 19,
    "shares": 18,
    "saves": 90,
    "linkTaps": 0
  },
  {
    "client": "LUDMILA MENDES",
    "access": "Ativo",
    "month": "OUTUBRO",
    "followers": 5496,
    "newFollowers": 2978,
    "losses": 1474,
    "reach": 36088,
    "views": 75648,
    "engagement": 454,
    "visits": null,
    "interactions": 794,
    "likes": 646,
    "comments": 23,
    "shares": 18,
    "saves": 41,
    "linkTaps": 0
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 11043,
    "newFollowers": 188,
    "losses": 109,
    "reach": 13849,
    "views": 54389,
    "engagement": 503,
    "visits": null,
    "interactions": 459,
    "likes": 250,
    "comments": 4,
    "shares": 10,
    "saves": 6,
    "linkTaps": 1
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 11063,
    "newFollowers": 101,
    "losses": 81,
    "reach": 3834,
    "views": 17657,
    "engagement": 242,
    "visits": null,
    "interactions": 144,
    "likes": 46,
    "comments": 5,
    "shares": 17,
    "saves": 1,
    "linkTaps": 1
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 11212,
    "newFollowers": 242,
    "losses": 93,
    "reach": 25542,
    "views": 101902,
    "engagement": 2181,
    "visits": null,
    "interactions": 3461,
    "likes": 2952,
    "comments": 136,
    "shares": 66,
    "saves": 25,
    "linkTaps": 1
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 11345,
    "newFollowers": 245,
    "losses": 111,
    "reach": 20375,
    "views": 97952,
    "engagement": 1787,
    "visits": null,
    "interactions": 2642,
    "likes": 2208,
    "comments": 67,
    "shares": 22,
    "saves": 16,
    "linkTaps": 2
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 11649,
    "newFollowers": 496,
    "losses": 192,
    "reach": 190583,
    "views": 384645,
    "engagement": 7208,
    "visits": null,
    "interactions": 10560,
    "likes": 8974,
    "comments": 265,
    "shares": 452,
    "saves": 90,
    "linkTaps": 0
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 11733,
    "newFollowers": 210,
    "losses": 130,
    "reach": 15456,
    "views": 32373,
    "engagement": 696,
    "visits": null,
    "interactions": 1123,
    "likes": 977,
    "comments": 18,
    "shares": 22,
    "saves": 8,
    "linkTaps": 2
  },
  {
    "client": "MARCELO MIDLEJ",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 11835,
    "newFollowers": 215,
    "losses": 108,
    "reach": 10688,
    "views": 55068,
    "engagement": 632,
    "visits": null,
    "interactions": 1838,
    "likes": 1591,
    "comments": 27,
    "shares": 38,
    "saves": 15,
    "linkTaps": 3
  },
  {
    "client": "PRIME ESTHETICS",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 613,
    "newFollowers": 104,
    "losses": 14,
    "reach": 5758,
    "views": 22322,
    "engagement": 155,
    "visits": null,
    "interactions": 222,
    "likes": 101,
    "comments": 2,
    "shares": 34,
    "saves": 40,
    "linkTaps": 0
  },
  {
    "client": "PRIME ESTHETICS",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 669,
    "newFollowers": 69,
    "losses": 12,
    "reach": 4837,
    "views": 14423,
    "engagement": 94,
    "visits": null,
    "interactions": 160,
    "likes": 98,
    "comments": 0,
    "shares": 22,
    "saves": 13,
    "linkTaps": 1
  },
  {
    "client": "PRIME ESTHETICS",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 674,
    "newFollowers": 15,
    "losses": 12,
    "reach": 59,
    "views": 4060,
    "engagement": 4,
    "visits": null,
    "interactions": 89,
    "likes": 56,
    "comments": 0,
    "shares": 11,
    "saves": 7,
    "linkTaps": 0
  },
  {
    "client": "PRIME ESTHETICS",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 682,
    "newFollowers": 28,
    "losses": 17,
    "reach": 13098,
    "views": 23946,
    "engagement": 42,
    "visits": null,
    "interactions": 96,
    "likes": 52,
    "comments": 2,
    "shares": 15,
    "saves": 9,
    "linkTaps": 0
  },
  {
    "client": "MASTER PELE",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 1071,
    "newFollowers": 51,
    "losses": 15,
    "reach": 8024,
    "views": 23149,
    "engagement": 176,
    "visits": null,
    "interactions": 291,
    "likes": 212,
    "comments": 43,
    "shares": 13,
    "saves": 20,
    "linkTaps": 1
  },
  {
    "client": "MASTER PELE",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 1101,
    "newFollowers": 46,
    "losses": 21,
    "reach": null,
    "views": 33269,
    "engagement": null,
    "visits": null,
    "interactions": 242,
    "likes": 164,
    "comments": 21,
    "shares": 7,
    "saves": 46,
    "linkTaps": 7
  },
  {
    "client": "NEUROAPTA",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 85,
    "newFollowers": 4,
    "losses": 120,
    "reach": 883,
    "views": 17,
    "engagement": 15,
    "visits": 70,
    "interactions": 66,
    "likes": 0,
    "comments": 1,
    "shares": 2,
    "saves": 0,
    "linkTaps": null
  },
  {
    "client": "NEUROCLÍNICA ALMIR PLESSIM",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 661,
    "newFollowers": 22,
    "losses": 5,
    "reach": 613,
    "views": 2899,
    "engagement": 39,
    "visits": 23,
    "interactions": 155,
    "likes": 136,
    "comments": 4,
    "shares": 3,
    "saves": 8,
    "linkTaps": 6
  },
  {
    "client": "NEUROCLÍNICA ALMIR PLESSIM",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 682,
    "newFollowers": 32,
    "losses": 10,
    "reach": 1157,
    "views": 3998,
    "engagement": 88,
    "visits": null,
    "interactions": 226,
    "likes": 178,
    "comments": 20,
    "shares": 2,
    "saves": 20,
    "linkTaps": 0
  },
  {
    "client": "NEUROCLÍNICA ALMIR PLESSIM",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 687,
    "newFollowers": 13,
    "losses": 8,
    "reach": 553,
    "views": 2603,
    "engagement": 55,
    "visits": null,
    "interactions": 141,
    "likes": 129,
    "comments": 4,
    "shares": 0,
    "saves": 8,
    "linkTaps": 0
  },
  {
    "client": "NEUROCLÍNICA ALMIR PLESSIM",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 709,
    "newFollowers": 24,
    "losses": 2,
    "reach": 649,
    "views": 1523,
    "engagement": 100,
    "visits": null,
    "interactions": 226,
    "likes": 205,
    "comments": 9,
    "shares": 0,
    "saves": 8,
    "linkTaps": 0
  },
  {
    "client": "RODRIGO DA GUARDA",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 2627,
    "newFollowers": 42,
    "losses": 41,
    "reach": 892,
    "views": 10255,
    "engagement": 69,
    "visits": null,
    "interactions": 321,
    "likes": 287,
    "comments": 1,
    "shares": 1,
    "saves": 9,
    "linkTaps": 0
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 5007,
    "newFollowers": 33,
    "losses": 21,
    "reach": 1202,
    "views": 7270,
    "engagement": 85,
    "visits": null,
    "interactions": 165,
    "likes": 140,
    "comments": 5,
    "shares": 2,
    "saves": 4,
    "linkTaps": 1
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 5004,
    "newFollowers": 16,
    "losses": 20,
    "reach": 3058,
    "views": 10060,
    "engagement": 102,
    "visits": null,
    "interactions": 245,
    "likes": 210,
    "comments": 13,
    "shares": 2,
    "saves": 3,
    "linkTaps": 0
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 5002,
    "newFollowers": 23,
    "losses": 25,
    "reach": 1664,
    "views": 10922,
    "engagement": 122,
    "visits": null,
    "interactions": 379,
    "likes": 304,
    "comments": 27,
    "shares": 2,
    "saves": 1,
    "linkTaps": 0
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 5004,
    "newFollowers": 37,
    "losses": 35,
    "reach": 1251,
    "views": 5521,
    "engagement": 67,
    "visits": null,
    "interactions": 199,
    "likes": 126,
    "comments": 45,
    "shares": 6,
    "saves": 1,
    "linkTaps": 3
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 4955,
    "newFollowers": 44,
    "losses": 91,
    "reach": 5497,
    "views": 21949,
    "engagement": 130,
    "visits": null,
    "interactions": 516,
    "likes": 358,
    "comments": 44,
    "shares": 44,
    "saves": 3,
    "linkTaps": 3
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 4959,
    "newFollowers": 31,
    "losses": 29,
    "reach": 1117,
    "views": 7081,
    "engagement": 89,
    "visits": null,
    "interactions": 252,
    "likes": 201,
    "comments": 12,
    "shares": 8,
    "saves": 0,
    "linkTaps": 2
  },
  {
    "client": "ROSE MEIRE",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 4970,
    "newFollowers": 33,
    "losses": 23,
    "reach": 1794,
    "views": 8234,
    "engagement": 94,
    "visits": null,
    "interactions": 289,
    "likes": 227,
    "comments": 8,
    "shares": 14,
    "saves": 1,
    "linkTaps": 2
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 4887,
    "newFollowers": 73,
    "losses": 61,
    "reach": 3334,
    "views": 24447,
    "engagement": 299,
    "visits": null,
    "interactions": 5071,
    "likes": 527,
    "comments": 36,
    "shares": 2225,
    "saves": 20,
    "linkTaps": 0
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 5076,
    "newFollowers": 250,
    "losses": 62,
    "reach": 8802,
    "views": 41149,
    "engagement": 1008,
    "visits": null,
    "interactions": 4156,
    "likes": 1245,
    "comments": 96,
    "shares": 1338,
    "saves": 56,
    "linkTaps": 0
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 5133,
    "newFollowers": 127,
    "losses": 74,
    "reach": 4236,
    "views": 25118,
    "engagement": 587,
    "visits": null,
    "interactions": 4308,
    "likes": 872,
    "comments": 101,
    "shares": 1619,
    "saves": 28,
    "linkTaps": 0
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 5152,
    "newFollowers": 113,
    "losses": 90,
    "reach": 2800,
    "views": 10512,
    "engagement": 310,
    "visits": null,
    "interactions": 1061,
    "likes": 440,
    "comments": 43,
    "shares": 257,
    "saves": 20,
    "linkTaps": 1
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 5197,
    "newFollowers": 124,
    "losses": 80,
    "reach": 1837,
    "views": 8164,
    "engagement": 142,
    "visits": null,
    "interactions": 407,
    "likes": 265,
    "comments": 7,
    "shares": 27,
    "saves": 11,
    "linkTaps": 0
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 5222,
    "newFollowers": 102,
    "losses": 74,
    "reach": 2457,
    "views": 9305,
    "engagement": 125,
    "visits": null,
    "interactions": 297,
    "likes": 227,
    "comments": 7,
    "shares": 5,
    "saves": 5,
    "linkTaps": 0
  },
  {
    "client": "SENGE",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 5221,
    "newFollowers": 78,
    "losses": 76,
    "reach": 38109,
    "views": 35950,
    "engagement": 42,
    "visits": null,
    "interactions": 106,
    "likes": 73,
    "comments": 2,
    "shares": 6,
    "saves": 3,
    "linkTaps": 1
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 53,
    "newFollowers": 1,
    "losses": 0,
    "reach": 3329,
    "views": 12963,
    "engagement": 33,
    "visits": null,
    "interactions": 52,
    "likes": 47,
    "comments": 0,
    "shares": 1,
    "saves": 3,
    "linkTaps": 4
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 66,
    "newFollowers": 13,
    "losses": 0,
    "reach": 4068,
    "views": 10527,
    "engagement": 26,
    "visits": null,
    "interactions": 32,
    "likes": 30,
    "comments": 0,
    "shares": 0,
    "saves": 2,
    "linkTaps": 5
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 147,
    "newFollowers": 84,
    "losses": 5,
    "reach": 9258,
    "views": 33355,
    "engagement": 85,
    "visits": null,
    "interactions": 133,
    "likes": 114,
    "comments": 2,
    "shares": 5,
    "saves": 6,
    "linkTaps": 16
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 215,
    "newFollowers": 83,
    "losses": 13,
    "reach": 9237,
    "views": 33857,
    "engagement": 84,
    "visits": null,
    "interactions": 111,
    "likes": 89,
    "comments": 3,
    "shares": 3,
    "saves": 10,
    "linkTaps": 19
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 264,
    "newFollowers": 59,
    "losses": 9,
    "reach": 9482,
    "views": 22632,
    "engagement": 78,
    "visits": null,
    "interactions": 101,
    "likes": 88,
    "comments": 1,
    "shares": 1,
    "saves": 7,
    "linkTaps": 25
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 323,
    "newFollowers": 70,
    "losses": 12,
    "reach": 8872,
    "views": 23987,
    "engagement": 95,
    "visits": null,
    "interactions": 130,
    "likes": 104,
    "comments": 3,
    "shares": 7,
    "saves": 7,
    "linkTaps": 9
  },
  {
    "client": "SERENITY",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 354,
    "newFollowers": 40,
    "losses": 8,
    "reach": 6413,
    "views": 19555,
    "engagement": 77,
    "visits": null,
    "interactions": 125,
    "likes": 97,
    "comments": 2,
    "shares": 6,
    "saves": 9,
    "linkTaps": 9
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 657,
    "newFollowers": 121,
    "losses": 12,
    "reach": 31682,
    "views": 182984,
    "engagement": 1374,
    "visits": null,
    "interactions": 2778,
    "likes": 1891,
    "comments": 101,
    "shares": 196,
    "saves": 32,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 664,
    "newFollowers": 20,
    "losses": 14,
    "reach": 6159,
    "views": 15564,
    "engagement": 592,
    "visits": null,
    "interactions": 717,
    "likes": 621,
    "comments": 47,
    "shares": 18,
    "saves": 8,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 674,
    "newFollowers": 18,
    "losses": 8,
    "reach": 4569,
    "views": 9551,
    "engagement": 91,
    "visits": null,
    "interactions": 142,
    "likes": 115,
    "comments": 1,
    "shares": 8,
    "saves": 3,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 680,
    "newFollowers": 18,
    "losses": 10,
    "reach": 6046,
    "views": 16232,
    "engagement": 167,
    "visits": null,
    "interactions": 266,
    "likes": 200,
    "comments": 9,
    "shares": 16,
    "saves": 2,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "MAIO",
    "followers": 688,
    "newFollowers": 10,
    "losses": 3,
    "reach": 3702,
    "views": 9369,
    "engagement": 102,
    "visits": null,
    "interactions": 215,
    "likes": 167,
    "comments": 4,
    "shares": 17,
    "saves": 4,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "JUNHO",
    "followers": 693,
    "newFollowers": 15,
    "losses": 12,
    "reach": 1753,
    "views": 3510,
    "engagement": 31,
    "visits": null,
    "interactions": 61,
    "likes": 46,
    "comments": 0,
    "shares": 5,
    "saves": 0,
    "linkTaps": 0
  },
  {
    "client": "SOBRAMID",
    "access": "Ativo",
    "month": "JULHO",
    "followers": 700,
    "newFollowers": 23,
    "losses": 14,
    "reach": 2963,
    "views": 7526,
    "engagement": 119,
    "visits": null,
    "interactions": 225,
    "likes": 167,
    "comments": 10,
    "shares": 18,
    "saves": 6,
    "linkTaps": 0
  },
  {
    "client": "YNTEGRA",
    "access": "Ativo",
    "month": "JANEIRO",
    "followers": 29,
    "newFollowers": 29,
    "losses": null,
    "reach": 6817,
    "views": 6013,
    "engagement": 19,
    "visits": null,
    "interactions": 54,
    "likes": 42,
    "comments": 0,
    "shares": 3,
    "saves": 6,
    "linkTaps": 3
  },
  {
    "client": "YNTEGRA",
    "access": "Ativo",
    "month": "FEVEREIRO",
    "followers": 109,
    "newFollowers": 83,
    "losses": 2,
    "reach": 64066,
    "views": 57365,
    "engagement": 192,
    "visits": null,
    "interactions": 287,
    "likes": 229,
    "comments": 6,
    "shares": 13,
    "saves": 23,
    "linkTaps": 45
  },
  {
    "client": "YNTEGRA",
    "access": "Ativo",
    "month": "MARÇO",
    "followers": 200,
    "newFollowers": 96,
    "losses": 6,
    "reach": 21792,
    "views": 49943,
    "engagement": 166,
    "visits": null,
    "interactions": 321,
    "likes": 225,
    "comments": 10,
    "shares": 19,
    "saves": 18,
    "linkTaps": 40
  },
  {
    "client": "YNTEGRA",
    "access": "Ativo",
    "month": "ABRIL",
    "followers": 214,
    "newFollowers": 22,
    "losses": 6,
    "reach": 2138,
    "views": 7954,
    "engagement": 101,
    "visits": null,
    "interactions": 207,
    "likes": 144,
    "comments": 6,
    "shares": 21,
    "saves": 1,
    "linkTaps": 6
  }
];
